import { cardLabel, names, type PlayingCard } from './common.ts';
import { analyseGin, type GinState, type MeldAnalysis } from './gin.ts';

function button(action: string, label: string, extra = '', disabled = false): string {
  return `<button data-action="${action}" ${extra} ${disabled ? 'disabled' : ''}>${label}</button>`;
}
function red(card: PlayingCard): string { return card.suit === '♥' || card.suit === '♦' ? 'ink-red' : ''; }
function melds(info: MeldAnalysis): string {
  return `<div class="gin-melds">${info.melds.length ? info.melds.map((meld, i) => `<div><small>組 ${i + 1}</small><span>${meld.map(cardLabel).join(' / ')}</span></div>`).join('') : '<p>組はまだありません。</p>'}<div class="gin-deadwood"><small>残り ${info.points}点</small><span>${info.deadwood.map(cardLabel).join(' / ') || 'なし'}</span></div></div>`;
}
export const ginRules = '52枚・各10枚、AIと1対1で100点先取。組は同じ数字3〜4枚、または同じスートの連番3枚以上。Aは1扱いでA-2-3は可、Q-K-Aは不可です。組に含まれないカード（残り）の点数はA=1、2〜10=数字、J/Q/K=10。組は残り点数が最小になるものを自動判定します。1枚引いて1枚捨て、捨てた後に残り10点以下ならノック、0点ならジン。ノック時は相手の組と付け札を含めて最小の残り点数を計算し、ノック側のほうが少なければ差分を獲得。相手が同点以下なら相手が差分＋25点（アンダーカット）。ジンは相手の残り＋25点、付け札不可。最初の捨て札は非ディーラー、ディーラーの順で取るか見送り、双方見送りなら山札から開始。取った捨て札は同じ手番に捨て直せません。山札が2枚になった手番で決着しなければ無得点で同じ配り手のまま配り直します。ビッグジン・追加ボーナスはありません。';
export function ginView(s: GinState, selected: string | null): string {
  const done = s.phase === 'roundOver' || s.phase === 'matchOver';
  const human = s.turn === 0 && !done, canSelect = human && s.phase === 'discard';
  const own = done ? s.result!.analyses[0] : analyseGin(s.hands[0]);
  const preview = selected ? analyseGin(s.hands[0].filter(c => c.id !== selected)) : null;
  const meldIndex = new Map(own.melds.flatMap((meld, i) => meld.map(c => [c.id, i + 1] as const)));
  const upcard = s.discard.at(-1);
  const canStock = human && s.phase === 'draw';
  const canUpcard = human && (s.phase === 'opening' || s.phase === 'draw' && !s.mustStock) && !!upcard;
  const end = s.result ? `<div class="result gin-result"><small>${s.phase === 'matchOver' ? 'MATCH FINISHED' : 'ROUND FINISHED'}</small><h2>${s.phase === 'matchOver' ? `${names[s.result.winner!]}が100点達成！` : s.result.kind === 'draw' ? '無得点 · 配り直し' : `${names[s.result.winner!]}が${s.result.points}点獲得！`}</h2><p>${s.result.kind === 'gin' ? 'ジン：相手の残り点数＋25点（付け札なし）' : s.result.kind === 'undercut' ? 'アンダーカット：点数差＋25点' : s.result.kind === 'knock' ? 'ノック成功：残り点数の差' : '山札が2枚になりました。同じディーラーで再開します。'}</p>${s.result.laidOff.length ? `<p>付け札（ノック側の組へ）：${s.result.laidOff.map(l => `${cardLabel(l.card)} → 組${l.meld + 1}`).join(' / ')}</p>` : ''}<details><summary>両者の組と残り点数を見る</summary>${[0, 1].map(p => `<h3>${names[p]} · ${s.result!.analyses[p].points}点${p === s.result!.knocker ? '（ノック側）' : ''}</h3>${melds(s.result!.analyses[p])}`).join('')}</details>${s.phase === 'matchOver' ? button('restart', '新しい対戦', 'class="primary wide"') : button('gin-next', s.result.kind === 'draw' ? '配り直す' : '次のラウンドへ', 'class="primary wide"')}${button('home', 'ゲームを選ぶ', 'class="secondary wide"')}</div>` : '';
  return `<div class="round-heading"><strong>ROUND ${s.round}</strong><span>100点先取</span></div><div class="scoreboard gin-score"><span class="${human ? 'current' : ''}">あなた <b>${s.scores[0]}</b></span><small>POINTS</small><span class="${s.turn === 1 && !done ? 'current' : ''}">AI ソラ <b>${s.scores[1]}</b></span></div><div class="gin-opponent"><span>AIの手札 ${s.hands[1].length}枚</span><span>配り手：${names[s.dealer]}</span></div><div class="status" role="status">${done ? s.message : `${names[s.turn]}の番 · ${s.message}`}</div><div class="gin-table"><div><small>山札 ${s.stock.length}枚</small>${button('gin-stock', '♣<span>山札から引く</span>', 'class="card-back draw-pile"', !canStock)}</div><div><small>捨て札</small>${upcard ? button('gin-upcard', `${cardLabel(upcard)}<small>捨て札から取る</small>`, `class="playing-card gin-upcard ${red(upcard)}"`, !canUpcard) : '<div class="gin-empty">引いた後<br>捨て札を選択</div>'}</div></div>${human && s.phase === 'opening' ? button('gin-decline', '最初の捨て札を見送る', 'class="secondary wide"') : ''}<div class="hand-heading">あなたの手札 <span>${s.hands[0].length}枚 · 残り${own.points}点</span></div><div class="hand gin-hand">${s.hands[0].map(c => button('gin-select', `<span>${cardLabel(c)}</span><small>${meldIndex.has(c.id) ? `組${meldIndex.get(c.id)}` : '残り'}</small>`, `class="playing-card ${red(c)} ${selected === c.id ? 'chosen' : ''}" data-id="${c.id}" aria-label="${cardLabel(c)}" aria-pressed="${selected === c.id}"`, !canSelect || c.id === s.forbiddenDiscard)).join('')}</div>${canSelect ? `<div class="gin-preview" role="status">${preview ? `このカードを捨てると、残り${preview.points}点${preview.points === 0 ? ' · ジン可能！' : preview.points <= 10 ? ' · ノック可能' : ''}` : '捨てるカードを1枚選んでください'}</div><div class="gin-actions">${button('gin-discard', '捨てる', 'class="secondary"', !selected)}${button('gin-knock', preview?.points === 0 ? '捨ててジン' : '捨ててノック', 'class="primary"', !preview || preview.points > 10)}</div><p class="hint">捨て札から取ったカードは、この手番では捨て直せません</p>` : !done ? '<p class="hint">山札か捨て札から引く → 1枚選んで捨てる</p>' : ''}<details class="gin-analysis" ${done ? '' : 'open'}><summary>組と残り点数（自動判定）</summary>${melds(own)}</details>${end}`;
}
