import { cardLabel, names } from './common.ts';
import { sevensSuits } from './sevens.ts';
import { canPassPointSevens, canUsePointSpecial, pointSpecialKinds, pointSpecialNames, pointSevensRanking, pointPlacementValue, type PointSevensState } from './point-sevens.ts';

export const pointSevensRules = '独自ルールの七並べ。自分＋AI3人、52枚・ジョーカーなし。7を自動配置して所有者に各＋2点、♦7の持ち主から開始。7から連続する位置に出すと＋2点。空いているA・K、またはA・K側から内側へ伸びる未接続の並びに出すと＋1点。穴を埋めて7側と接続する一手は＋2点、過去の得点は変更しません。AとKはつながりません。パスは毎回－1点で、脱落・回数制限なし。対戦中の全員が連続パスすると強制配置になり、出せる人は必ず1枚出すまで続きます。出せない人のパスも－1点。配置で連続パスと強制配置をリセット。最後の1人は1枚出す最終手番の後、残り手札1枚につき－1点で終了。ラウンドの得点順、同点はあがった順です。全員に特殊カードをランダムに1枚配布（重複あり）。得点優位は次の自分の配置まで、自分の配置が＋2点・他の人は＋1点。重複時は効果を持つ人が＋2点。効果を終える配置にも適用し、割り込み・自分の指定配置でも終了。指定配置は好きな空き位置を持ち主が即配置して固定＋2点、使用者にも＋2点（自分指定なら＋4点）。連続配置は使用した手番を終了し、次の通常手番だけ最大2枚。2枚出せたらその合計点を2倍、1枚だけなら通常点。パス・別特殊で失効。パス免除は所持中の通常パスの減点を自動で最大3回免除、強制配置中の出せないパスも対象。持ち札渡しは相手に通常カードを1枚渡して＋1点、相手が任意の手札から割り込み配置したら使用者にさらに＋1点。相手自身も配置点を獲得して元の順番に戻ります。割り込みは辞退可能で無減点、最後の1人なら最終の1枚として必ず配置。特殊カードだけを持っていてもあがれ、未使用分は失効します。強制配置・最終手番・割り込み中は特殊カードを使えません。次のラウンドでは累計を引き継ぎ、前ラウンド最下位が配布後に特殊カードを追加で1枚選びます。優位・予約はラウンドごとにリセット。';
export interface PointSelection { specialId: string | null; cardId: string | null; target: number | null; }
const effectDescriptions = { flip: '次の自分の配置まで、自分の配置は＋2点・他の人は＋1点。効果を持つ人同士は＋2点。この手番は終了。', force: '空き位置を持ち主が即配置して＋2点、使用者にも＋2点。自分指定なら＋4点。', double: 'この手番は終了。次の通常手番で最大2枚。2枚出せたらその合計点を2倍、1枚だけなら通常点。パス・別特殊で失効。', freePass: '持っている間、通常パスの減点を自動で最大3回免除。全員パスには算入。', gift: '相手へ通常カードを1枚渡して＋1点。相手は任意の手札から最大1枚割り込み配置でき、配置したら使用者にさらに＋1点。' };
export function pointSevensView(s: PointSevensState, selection: PointSelection = { specialId: null, cardId: null, target: null }): string {
  const human = s.turn === 0 && !['done','choice'].includes(s.phase), laid = new Set(s.board.map(c => c.id));
  const values = new Map(s.hands[0].map(c => [c.id, pointPlacementValue(s, c, 0)]));
  const selected = s.specials[0].find(c=>c.id===selection.specialId);
  const ranks = ['', 'A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'];
  const board = sevensSuits.map(suit => `<div class="sevens-row ${suit === '♥' || suit === '♦' ? 'red-row' : ''}" role="group" aria-label="${suit}の場"><strong aria-hidden="true">${suit}</strong><div>${Array.from({ length: 13 }, (_, i) => {
    const rank = i + 1, id = `${suit}${rank}`, value = values.get(id) ?? 0;
    return `<span class="sevens-cell ${laid.has(id) ? 'laid' : ''} ${rank === 7 ? 'seven' : ''} ${human && value ? 'available' : ''} ${human && value === 1 ? 'point-one' : ''}" aria-label="${suit} ${ranks[rank]} ${laid.has(id) ? '配置済み' : '空き'}${human && value ? ` ＋${value}点` : ''}">${ranks[rank]}</span>`;
  }).join('')}</div></div>`).join('');
  const rankList = s.phase === 'done' ? `<div class="result"><small>GAME FINISHED</small><h2>得点での順位</h2><ol class="rank-list">${pointSevensRanking(s).map((p, i) => {
    const placed = Object.values(s.placements).filter(v => v.player === p).reduce((sum, v) => sum + v.points, 0);
    return `<li><strong>${i + 1}位</strong><span>${names[p]} · ${s.scores[p]}点<small>配置＋${placed} ／ ボーナス＋${s.bonuses[p]} ／ パス－${s.passes[p]-s.freePasses[p]} ／ 残り－${s.penalties[p]}<br>累計 ${s.totals[p]}点</small></span></li>`;
  }).join('')}</ol><p class="hint">今回の順位 · 同点はあがった順で決定</p><button data-action="point-next" class="primary wide">次のラウンドへ</button><button data-action="restart" class="secondary wide">累計をリセットして遊ぶ</button><button data-action="home" class="secondary wide">ゲームを選ぶ</button></div>` : '';
  const bonus = s.phase === 'choice' ? `<div class="point-alert"><strong>前ラウンド最下位の追加カード</strong><p>${names[s.bonusOwner!]}が手札と配布カードを見て1枚選びます。</p>${s.bonusOwner===0 ? pointSpecialKinds.map(kind=>`<button class="secondary wide" data-action="point-bonus" data-kind="${kind}">${pointSpecialNames[kind]}を追加</button><p class="hint">${effectDescriptions[kind]}</p>`).join('') : '<p>AIが選んでいます…</p>'}</div>` : '';
  const specials = `<section class="point-specials"><h2>あなたの特殊カード</h2><p class="hint">通常の手札がなくなればあがり · 未使用分は失効</p>${s.specials[0].map(c=>`<button data-action="point-special" data-id="${c.id}" class="secondary wide" ${human&&canUsePointSpecial(s,c.id)?'':'disabled'}>${pointSpecialNames[c.kind]}${c.kind==='freePass'?` · 残り${c.remaining??3}回（自動）`:''}</button>`).join('') || '<p class="hint">特殊カードはありません。</p>'}${s.doubleReady[0] ? '<p class="point-alert">連続配置を予約済み · 次の自分の手番だけ最大2枚</p>' : ''}</section>`;
  const menu = selected && human && canUsePointSpecial(s,selected.id) ? `<section class="point-special-panel" aria-labelledby="point-special-title"><h2 id="point-special-title">${pointSpecialNames[selected.kind]}を使う</h2><p>${effectDescriptions[selected.kind]}</p>${selected.kind==='force' ? `<div class="point-target-grid">${sevensSuits.map(suit=>`<strong>${suit}</strong>${Array.from({length:13},(_,i)=>({id:`${suit}${i+1}`,rank:i+1,suit})).filter(c=>!laid.has(c.id)).map(c=>`<button class="secondary" data-action="point-card" data-id="${c.id}" aria-pressed="${selection.cardId===c.id}" aria-label="指定 ${cardLabel(c)}">${cardLabel(c)}</button>`).join('')}`).join('')}</div>` : selected.kind==='gift' ? `<p>渡すカード</p><div class="point-target-grid">${s.hands[0].map(c=>`<button class="secondary" data-action="point-card" data-id="${c.id}" aria-pressed="${selection.cardId===c.id}">${cardLabel(c)}を渡す</button>`).join('')}</div><p>渡す相手</p>${[1,2,3].filter(p=>!s.finishOrder.includes(p)).map(p=>`<button class="secondary wide" data-action="point-target" data-target="${p}" aria-pressed="${selection.target===p}">${names[p]}へ渡す</button>`).join('')}` : ''}<button class="primary wide" data-action="point-use-special" ${selected.kind==='force'&&!selection.cardId||selected.kind==='gift'&&(!selection.cardId||selection.target===null)?'disabled':''}>この効果を使う</button><button class="secondary wide" data-action="point-cancel">キャンセル</button></section>` : '';
  return `<div class="round-heading"><strong>ROUND ${s.round}</strong><span>${s.advantage.some(Boolean)?'得点優位が有効':'7側＋2 · 未接続＋1'}</span></div><div class="point-scores">${[0, 1, 2, 3].map(p => `<div class="${s.phase !== 'done' && s.turn === p ? 'active' : ''}"><small>${names[p]}</small><strong>${s.scores[p]}<small>点</small></strong><span>${s.finishOrder.includes(p) ? `${s.finishOrder.indexOf(p) + 1}番あがり` : `${s.hands[p].length}枚`}<br>特殊${s.specials[p].length}枚${s.advantage[p]?' · 優位':''}<br>累計${s.totals[p]+(s.phase==='done'?0:s.scores[p])}点</span></div>`).join('')}</div><div class="status" role="status">${s.phase === 'done' ? s.message : `${names[s.turn]}の番 · ${s.message}`}</div>${bonus}${s.phase==='done' ? '' : s.phase === 'final'||s.phase==='interrupt'&&s.interrupt!.final ? '<p class="point-alert">最終手番：1枚出すと終了。残り手札は1枚につき－1点</p>' : s.phase==='interrupt' ? '<p class="point-alert">割り込み配置 · 最大1枚。通常の手番は消費しません</p>' : s.remainingPlays===2||s.placedThisTurn>0 ? `<p class="point-alert">連続配置 · あと${s.remainingPlays}枚出せます</p>` : s.forced ? '<p class="point-alert">強制配置中 · 特殊カードは使えません</p>' : `<p class="hint">連続パス ${s.consecutivePasses} / ${4 - s.finishOrder.length}人 · 1周で強制配置</p>`}<div class="sevens-board" aria-label="ポイント七並べの場">${board}</div><p class="hint">金色の枠：＋2点 ／ 青色の枠：＋1点</p><div class="hand-heading">あなたの手札 <span>${s.hands[0].length}枚 · ${s.scores[0]}点</span></div><div class="hand sevens-hand point-hand">${s.hands[0].map(c => {
    const value = values.get(c.id)!;
    return `<button data-action="point-sevens-play" data-id="${c.id}" aria-label="${cardLabel(c)}${value ? ` ＋${value}点` : ''}" class="playing-card ${c.suit === '♥' || c.suit === '♦' ? 'ink-red' : ''} ${value === 1 ? 'point-one' : ''}" ${!human || !value || selected ? 'disabled' : ''}><span>${cardLabel(c)}</span><small>${value ? `＋${value}点` : '待ち'}</small></button>`;
  }).join('') || `<p>あがりました。${s.phase==='done'?'':'残りの対戦を見守ろう。'}</p>`}</div>${s.phase !== 'done' ? `<button data-action="point-sevens-pass" class="secondary wide" ${human && canPassPointSevens(s) && !selected ? '' : 'disabled'}>${s.specials[0].some(c=>c.kind==='freePass')?'パス（自動免除・0点）':'パス（－1点）'}</button>` : ''}${human&&s.phase==='play'&&s.placedThisTurn>0 ? '<button class="secondary wide" data-action="point-end">1枚で手番終了</button>' : ''}${human&&s.phase==='interrupt'&&!s.interrupt!.final ? '<button class="secondary wide" data-action="point-interrupt-end">配置せず通常手番へ戻る</button>' : ''}<p class="hint">手札は横にスワイプ · 点数の付いたカードをタップして出す</p>${s.phase!=='done'?specials:''}${menu}${rankList}`;
}
