import { cardLabel, names } from './common.ts';
import { canPlaceSevens, sevensSuits, type SevensState } from './sevens.ts';

export const sevensRules = '自分とAI3人、52枚・ジョーカーなし。配札後に全員の7を場へ自動配置し、♦7の持ち主から開始します。同じマークで場のカードに隣接する空き位置へ1枚出します。AとKはつながりません。出せるカードがあってもパス可能。パスは各3回までで、4回目は脱落し残りの手札をすべて場へ配置します。離れて置かれたカードの隣にも出せます。手札をなくした順に上位、脱落した順に最下位・次の下位を確定。最後の1人は残った順位で終了します。';
function standing(s: SevensState, p: number): string {
  return s.outcomes[p] === 'playing' ? `${s.hands[p].length}枚 · パス残り${3 - s.passes[p]}回` : `${s.ranks[p]}位 · ${s.outcomes[p] === 'dropped' ? '脱落' : s.outcomes[p] === 'last' ? '最後の1人' : 'あがり'}`;
}
export function sevensView(s: SevensState): string {
  const human = !s.done && s.turn === 0 && s.outcomes[0] === 'playing';
  const laid = new Set(s.board.map(c => c.id));
  const canPlay = new Set(s.hands[0].filter(c => canPlaceSevens(s.board, c)).map(c => c.id));
  const ranks = ['', 'A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'];
  const board = sevensSuits.map(suit => `<div class="sevens-row ${suit === '♥' || suit === '♦' ? 'red-row' : ''}" role="group" aria-label="${suit}の場"><strong aria-hidden="true">${suit}</strong><div>${Array.from({ length: 13 }, (_, i) => { const rank = i + 1, id = `${suit}${rank}`; return `<span class="sevens-cell ${laid.has(id) ? 'laid' : ''} ${rank === 7 ? 'seven' : ''} ${human && canPlay.has(id) ? 'available' : ''}" aria-label="${suit} ${ranks[rank]} ${laid.has(id) ? '配置済み' : '空き'}">${ranks[rank]}</span>`; }).join('')}</div></div>`).join('');
  return `<div class="round-heading"><strong>SEVENS</strong><span>パスは3回まで</span></div><div class="opponents">${[1, 2, 3].map(p => `<div class="opponent ${!s.done && s.turn === p ? 'active' : ''}"><div class="avatar">${['S', 'M', 'R'][p - 1]}</div><strong>${names[p]}</strong><span>${standing(s, p)}</span></div>`).join('')}</div><div class="status" role="status">${s.done ? s.message : `${names[s.turn]}の番 · ${s.message}`}</div><div class="sevens-board" aria-label="七並べの場">${board}</div><p class="hint">明るい数字は配置済み · 金色の枠はあなたが出せる位置</p><div class="hand-heading">あなたの手札 <span>${standing(s, 0)}</span></div><div class="hand sevens-hand">${s.hands[0].map(c => `<button data-action="sevens-play" data-id="${c.id}" aria-label="${cardLabel(c)}" class="playing-card ${c.suit === '♥' || c.suit === '♦' ? 'ink-red' : ''}" ${!human || !canPlay.has(c.id) ? 'disabled' : ''}>${cardLabel(c)}</button>`).join('') || `<p>${s.outcomes[0] === 'dropped' ? '脱落しました。' : 'あがりました。'}${s.done ? '' : '残りの対戦を見守ろう。'}</p>`}</div>${!s.done ? `<button data-action="sevens-pass" class="secondary wide" ${human ? '' : 'disabled'}>${s.outcomes[0] !== 'playing' ? '順位確定 · 観戦中' : s.passes[0] === 3 ? 'パスして脱落（4回目）' : `パス（残り${3 - s.passes[0]}回）`}</button><p class="hint">手札は横にスワイプ · 明るいカードをタップして出す</p>` : `<div class="result"><small>GAME FINISHED</small><h2>今回の順位</h2><ol class="rank-list">${[0, 1, 2, 3].sort((a, b) => s.ranks[a]! - s.ranks[b]!).map(p => `<li><strong>${s.ranks[p]}位</strong><span>${names[p]} · ${s.outcomes[p] === 'dropped' ? '脱落' : s.outcomes[p] === 'last' ? '最後の1人' : 'あがり'}</span></li>`).join('')}</ol><button data-action="restart" class="primary wide">もう一度遊ぶ</button><button data-action="home" class="secondary wide">ゲームを選ぶ</button></div>`}`;
}
